import mongoose from 'mongoose'

const SchemeSchema = new mongoose.Schema({
  slug: { type: String, unique: true },
  name: { type: String, required: true },
  nameHi: { type: String, default: '' },
  nameTe: { type: String, default: '' },
  nameKn: { type: String, default: '' },
  nameMl: { type: String, default: '' },
  nameTa: { type: String, default: '' },
  description: { type: String, default: '' },
  descriptionHi: { type: String, default: '' },
  descriptionTe: { type: String, default: '' },
  descriptionKn: { type: String, default: '' },
  descriptionMl: { type: String, default: '' },
  descriptionTa: { type: String, default: '' },
  category: { type: String, default: '' },
  categoryHi: { type: String, default: '' },
  categoryTe: { type: String, default: '' },
  categoryKn: { type: String, default: '' },
  categoryMl: { type: String, default: '' },
  categoryTa: { type: String, default: '' },
  ministry: { type: String, default: '' },
  ministryHi: { type: String, default: '' },
  ministryTe: { type: String, default: '' },
  ministryKn: { type: String, default: '' },
  ministryMl: { type: String, default: '' },
  ministryTa: { type: String, default: '' },
  benefits: { type: [String], default: [] },
  benefitsHi: { type: [String], default: [] },
  benefitsTe: { type: [String], default: [] },
  benefitsKn: { type: [String], default: [] },
  benefitsMl: { type: [String], default: [] },
  benefitsTa: { type: [String], default: [] },
  documents: { type: [String], default: [] },
  documentsHi: { type: [String], default: [] },
  documentsTe: { type: [String], default: [] },
  documentsKn: { type: [String], default: [] },
  documentsMl: { type: [String], default: [] },
  documentsTa: { type: [String], default: [] },
  applyUrl: { type: String, default: '' },
  officialUrl: { type: String, default: '' },
  deadline: { type: String, default: '' }
}, { timestamps: true })

export default mongoose.model('Scheme', SchemeSchema)
